pre-release-commit-message = "chore: Release link-bridge v{{version}}"
tag-message = "{{tag_name}}"
tag-name = "link-bridge-v{{version}}"
pre-release-hook = ["./release-hook.sh"]
pre-release-replacements = [
    { file = "README.md", search = "link-bridge = \"\\d+\\.\\d+\\.\\d+\"", replace = "link-bridge = \"{{version}}\"", exactly = 1 },
    { file = "src/lib.rs", search = "link-bridge = \"\\d+\\.\\d+\\.\\d+\"", replace = "link-bridge = \"{{version}}\"", exactly = 1 },
]
